### ISSUE TITLE
Proto Quaternion definition

### ISSUE THREAD

**Issue by YoshuaNava** [ros-industrial/abb_libegm#11]
Hej,
In the [protobuf definition of Quaternion](https://github.com/ros-industrial/abb_libegm/blob/58ba9799ba9f0a71b5a9beafc7c502cdfb30ec83/proto/egm_wrapper.proto#L115), it is not very clear to which quaternion dimension each field corresponds, e.g:

Is it the case that

```
u1 = x
u2 = y
u3 = z
u4 = w
```

Or

```
u1 = w
u2 = x
u3 = y
u4 = z
```

for a quaternion defined as w + x **i** + y **j** + z **k** ?

Thank you.

**Comment by jontje** [comment]
Hej!

It is the second one:
```
u1 = w 
u2 = x
u3 = y
u4 = z
```

It follows the same definition as the RAPID data type `orient`

**Comment by gavanderhoorn** [comment]
@jontje: would this be something to add as a comment in the `.proto` file?

**Comment by jontje** [comment]
Definitely, I will do that

**Comment by gavanderhoorn** [comment]
@jontje: not sure, but I believe this one can be closed looking at:

https://github.com/ros-industrial/abb_libegm/blob/a278b7b580f0e2006a9c3c1b1e07dcff9552aef6/proto/egm_wrapper.proto#L126

**Comment by jontje** [comment]
@gavanderhoorn: Yes, it can be closed, thanks for the reminder! 👍
