### ISSUE TITLE
EGM for current or torque sensing

### ISSUE THREAD

**Issue by AbdElRahmanFarhan** [ros-industrial/abb_libegm#112]
Hello, 
I just have a question. Can EGM or Even RWS be used to get the current or torque of the motors?

**Comment by jontje** [comment]
As far as I know, then EGM cannot currently do that.

See https://github.com/ros-industrial/abb_libegm/issues/86#issuecomment-595839429 for one way of how RWS could be used (i.e. the "option 2" section). Also, please note that RWS is not designed for high performance.

**Comment by gavanderhoorn** [comment]
As this is not an issue with the library in this repository, and @jontje has answered the question, I'm closing it.

Feel free to keep commenting on the issue of course.
