### ISSUE TITLE
Any example to showcase the usage of this library?

### ISSUE THREAD

**Issue by ScottYang1982** [ros-industrial/abb_libegm#117]
HI,
Any example to showcase the usage of this library?
For example, a c++ main program to call the library to send some targets to robot ?
Thank you!

**Comment by gavanderhoorn** [comment]
See some of the later comments on #18.

And in a way, [ros-industrial/abb_robot_driver](https://github.com/ros-industrial/abb_robot_driver) is a "showcase" for this package (combined with `abb_librws`).

**Comment by gavanderhoorn** [comment]
I'm going to close this as it seems like it's a duplicate of #18.

Feel free to keep commenting on it @ScottYang1982, or on #18 if it's more on-topic there.
