### ISSUE TITLE
State Machine add-in is not available any more in the RoboApps ( Robot Studio )

### ISSUE THREAD

**Issue by nkquynh98** [ros-industrial/abb_libegm#149]
Hi everyone,

I am setting up a new Irb1200 robot with IR5C controller. I want to control the robot remotely using ROS ABB. However, when I follow the instruction for installing the egm on abb, I cannot find the add-in State Machine anymore in the RobotApps section in Robot Studio. I remember that it used to be in there one year ago, but now it has been removed. 

Could anyone help me with this problem? Or does anyone still have the StateMachine add-in setup file ( Statemachine.rspak ) and could share it with me? 

Thank you all.

**Comment by TheodoroCardoso** [comment]
Hi @nkquynh98,

We're facing the exact same problem.
Have you managed to solve it by any chance?

**Comment by mohamedamrali1993** [comment]
Hi @nkquynh98 & @TheodoroCardoso,

I am having the same problem and I am brand new to RAPID and the entire ABB framework.

I found a [repo](https://github.com/ITI-THM/statemachine_add_in_rw7) in this [open issue](https://github.com/ros-industrial/abb_robot_driver/issues/39) that has the 2.0.0 version for RW7, I think it is intended for Omnicore controllers and my IRC5 has RW6.13 . Thought this might be helpful, would either of you try to install it and let me know? 

Unfortunately, I don't have RobotStudio (licensed version) yet, so I don't have a complete picture of the APP but one place I'd check is under the Add-Ins tab.

[Issue 77](https://github.com/ros-industrial/abb_libegm/issues/77) talks about plans to host it.

@jontje and @gavanderhoorn , sorry to @ you but we really need your help! The MachineState Add-in is no longer hosted on the ABB RobotApps website. We would super appreciate it if you can open-source it. Please and thank you!

**Comment by bryangd34** [comment]
Hello @mohamedamrali1993,

Were you able to find the Statemachine Add-in for your IRC5 controller? I too am looking for it.
Thank you.

**Comment by gavanderhoorn** [comment]
According to [RobotApps website has reached its end of life](https://forums.robotstudio.com/discussion/13528/robotapps-website-has-reached-its-end-of-life) on the RobotStudio Forums, ABB has decided to shut down the RobotApps site. This was posted in July 2022.

The post seems to imply only "official ABB add-ins" will be downloadable from within RobotStudio from then on.

It's very likely the way we published the StateMachine Add-in makes it "unofficial", hence the disappearance.

I'll see if this situation can be resolved properly, but for now, here is a copy of the add-in's installation files: [ABB.StateMachine-1.1.zip](https://github.com/ros-industrial/abb_libegm/files/10754679/ABB.StateMachine-1.1.zip).

I've not tested extensively, but you should be able to make RobotStudio "see" the add-in by extracting the `.zip` and moving the `ABB.StateMachine-1.1` directory to `C:\ProgramData\ABB\DistributionPackages`. After a restart, RS should pick it up and it should be available for installation on your IRC5.

NOTE: this is the RW6.x compatible version of the add-in. There is *no* official RW7 version.

Thanks to @dave992 for finding a copy of the add-in's installation files.
