### ISSUE TITLE
Migrate to target RobotWare 6.07 or later

### ISSUE THREAD

**Issue by jontje** [ros-industrial/abb_libegm#19]
As per title.

**Comment by robinzhoucmu** [comment]
Are there documentation on how the communication interface is changed after robotware 6.07?

**Comment by jontje** [comment]
Hi @robinzhoucmu,

Yes, it is all specified in the RobotWare release notes: [Release Notes RW 6.07.pdf](https://github.com/ros-industrial/abb_libegm/files/2432807/Release.Notes.RW.6.07.pdf)

**Comment by gavanderhoorn** [comment]
Now that #32 has been merged we can close this one.
