### ISSUE TITLE
Improve state management in EGMTrajectoryInterface

### ISSUE THREAD

**Issue by jontje** [ros-industrial/abb_libegm#38]
The internal states that [EGMTrajectoryInterface](https://github.com/ros-industrial/abb_libegm/blob/master/include/abb_libegm/egm_trajectory_interface.h) can be in is:
* Normal trajectory execution
* Ramping down current references
* Tracking a static goal

Right now, it can be a bit difficult to follow how the states and sub states are changed and this can be simplified.

**Comment by gavanderhoorn** [comment]
Can we close this one @jontje, or is there still more work to do here?

**Comment by jontje** [comment]
Solved by https://github.com/ros-industrial/abb_libegm/pull/40
