### ISSUE TITLE
Add feedback to user interaction for EGMTrajectoryInterface

### ISSUE THREAD

**Issue by jontje** [ros-industrial/abb_libegm#39]
The following user interaction methods for [EGMTrajectoryInterface](https://github.com/ros-industrial/abb_libegm/blob/master/include/abb_libegm/egm_trajectory_interface.h) should return feedback to the user, so that it is clear if the interaction was accepted or not:
* `addTrajectory(...)`
* `stop(...)`
* `resume(...)`
* `updateDurationFactor(...)`
* `startStaticGoal(...)`
* `setStaticGoal(...)`
* `finishStaticGoal(...)`

**Comment by gavanderhoorn** [comment]
Can we close this one @jontje, or is there still more work to do here?

**Comment by jontje** [comment]
Solved by PR https://github.com/ros-industrial/abb_libegm/pull/40
