### ISSUE TITLE
EGM read joint angle always 57 times larger

### ISSUE THREAD

**Issue by Thompson104** [ros-industrial/abb_libegm#42]
Hi All,

We were using the EGM to do real-time control and want to move the robot 4th joint, for example, from 0 degree to 30 degree. The simulation on robot studio works just fine. However, the joint angle reading changes from 0 to 1710, instead of 0 to 30, when we run the experiments on the real robot. We tested all the joints and the angle reading almost always has to be divided by 57 to get a seeming accurate reading. Since we are doing real-time control, this reading is vital to us and we would like to have an accurate reading, if possible.

I wonder if you may know what's going on. The customer service agent was not responding to our questions since they don't know this EGM library...

Thank you.

**Comment by gavanderhoorn** [comment]
Which version of RobotWare do you have installed on the controller?

And which version of `abb_libegm` are you using?

**Comment by Thompson104** [comment]
@gavanderhoorn Thank you for your quick response. We were using the 6.06 robotware and I believe we have the most recent abb_libegm.

**Comment by gavanderhoorn** [comment]
> We were using the 6.06 robotware and I believe we have the most recent abb_libegm.

That would be the problem then.

**Comment by Thompson104** [comment]
Oh man, thank you. Previously the abb_libegm does not work with robotware versions earlier than the 6.07. I didn't notice the update. 

Thank you.

**Comment by Thompson104** [comment]
We will be testing the robot now to see if works.

**Comment by gavanderhoorn** [comment]
Closing this as it would seem to be a user configuration issue.

**Comment by gavanderhoorn** [comment]
@jontje: would there be some way we could add some sort of version detection to `abb_libegm` to prevent situations like this?

With `abb_librws` that would probably be possible, but with just `abb_libegm`?

**Comment by jontje** [comment]
> @jontje: would there be some way we could add some sort of version detection to `abb_libegm` to prevent situations like this?
> 
> With `abb_librws` that would probably be possible, but with just `abb_libegm`?

It should be possible to detect if proto fields introduced in the new EGM protocol is missing or not, I will investigate.

**Comment by gavanderhoorn** [comment]
Tracking version checking in #46.
