### ISSUE TITLE
Compatibility with RW 6.10

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/abb_libegm#61]
I've ran into a controller that was updated to RW `6.10`.

The readme currently states that only <del>`6.07`</del> `6.08` has been tested, but are there any known incompatibilities between `abb_libegm` and RW `6.10`?

**Comment by jontje** [comment]
I have only made a few brief tests with RobotWare `6.10`, and `abb_libegm` works as expected as far as I have seen.

**Comment by gavanderhoorn** [comment]
Closing as it would seem there are no expected incompatibilities.

We can re-open when that turns out to be `false`.
