### ISSUE TITLE
Improve verification of outbound EGM commands

### ISSUE THREAD

**Issue by jontje** [ros-industrial/abb_libegm#69]
As mentioned in PR https://github.com/ros-industrial/abb_libegm/issues/68, then there is currently no check in `abb_libegm` for NaN values. If NaN values are allowed to pass to the robot controller, then this will cause a system failure.

It should be straight-forward to add checks for NaN to the methods [here](https://github.com/ros-industrial/abb_libegm/blob/fc647bda83d670437f10e27fcab24fb2ac242e9a/src/egm_base_interface.cpp#L447) and [here](https://github.com/ros-industrial/abb_libegm/blob/fc647bda83d670437f10e27fcab24fb2ac242e9a/src/egm_base_interface.cpp#L572).

**Comment by gavanderhoorn** [comment]
@jontje: I've replaced the links with perma-links.
