### ISSUE TITLE
"No syntax specific" warning when compiling protobuf messages

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/abb_libegm#72]
We may want to add a `syntax` key to the `.proto` files we ship here ([these](https://github.com/ros-industrial/abb_libegm/tree/59b6b94cf1cc79135f05fc2b43dbacb625172e78/proto)):

```
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: egm.proto.
Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
```

**Comment by gavanderhoorn** [comment]
@jontje: we can do this for the `.proto`s we added for `abb_libegm` in this repository, but the main `egm.proto` is not maintained here.

That doesn't mean we cannot add the key, but it would be nice if "upstream" could do it as well.

**Comment by jontje** [comment]
> That doesn't mean we cannot add the key, but it would be nice if "upstream" could do it as well.

I have mentioned it to the EGM developers.

I will add the syntax specifier to `egm.proto` when I update for the newest protocol version.
