### ISSUE TITLE
RobotWare versions 6.0 - 6.06.03 are not supported currently

### ISSUE THREAD

**Issue by jontje** [ros-industrial/abb_libegm#82]
When PR #81 has been merged it would be possible to re-add support for the currently incompatible RobotWare versions 6.0 - 6.06.03.

**Comment by gavanderhoorn** [comment]
Hm. That didn't work as I had expected.

But great work with #81.

**Comment by gavanderhoorn** [comment]
@jontje: I've 'inverted' the title of this issue to better reflect the current state of things.

That turns this issue into an actual issue, instead of an enhancement request.

I'll also pin the issue, so users looking at the issue tracker would immediately see it.

**Comment by gavanderhoorn** [comment]
As `6.06` is really rather old now, I'm going to close this -- but keep it pinned.

If/when someone really wants to interface with such an old RW version, this issue could be used to track any related development.
